### ISSUE TITLE
Fast-Forward as Toggle, not Press-and-Hold!

### ISSUE THREAD

**Issue by DunhamGitHub** [budude2/openfgpa-GBC#32] opened 2024-01-13 12:33 UTC
Toggle Fast-Foward instead of "hold".

**Comment by shavitush** [comment] 2024-01-13 13:26
that exists, just press the button quickly once. it'll keep fast forwarding until you press it again

**Comment by pyth27** [comment] 2024-01-13 15:09
Duplicate of #12

**Closed** 2024-01-14 00:01 UTC
